import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export function generateDashboardReport(params: {
  title: string
  generatedAt: string
  filters: {
    yearRange: string
    selectedCrops: string
    selectedCountry: string
  }
  inputParams?: {
    temperature?: number
    precipitation?: number
    co2Emissions?: number
    fertilizerUse?: number
    soilHealthIndex?: number
    irrigationAccess?: number
    cropType?: string
  }
  metrics: {
    avgTemperature: string
    avgRainfall: number
    avgSoilHealth: string
    avgYield: string
  }
  predictionResult?: {
    predictedYield: number
    status: string
    confidence: string
    recommendation: string
    adaptationStrategy: string
  }
  tableData: any[]
}) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Title
  doc.setFontSize(20)
  doc.setTextColor(43, 106, 79)
  doc.text('YieldSim DSS — Dashboard Report', pageWidth / 2, 20, { align: 'center' })

  doc.setFontSize(11)
  doc.setTextColor(100)
  doc.text(`Generated: ${params.generatedAt}`, pageWidth / 2, 28, { align: 'center' })

  // Section: Applied Filters
  doc.setFontSize(13)
  doc.setTextColor(30)
  doc.text('Applied Filters', 14, 40)
  autoTable(doc, {
    startY: 44,
    head: [['Filter', 'Value']],
    body: [
      ['Year Range', params.filters.yearRange],
      ['Crops Selected', params.filters.selectedCrops],
      ['Country', params.filters.selectedCountry],
    ],
    headStyles: { fillColor: [43, 106, 79] },
    theme: 'grid',
  })

  // Section: Input Parameters (if prediction was run)
  if (params.inputParams) {
    const yAfterFilters = (doc as any).lastAutoTable.finalY + 8
    doc.setFontSize(13)
    doc.text('Input Parameters', 14, yAfterFilters)
    autoTable(doc, {
      startY: yAfterFilters + 4,
      head: [['Parameter', 'Value']],
      body: [
        ['Crop Type', params.inputParams.cropType ?? '—'],
        ['Temperature (°C)', String(params.inputParams.temperature ?? '—')],
        ['Precipitation (mm)', String(params.inputParams.precipitation ?? '—')],
        ['CO₂ Emissions (MT)', String(params.inputParams.co2Emissions ?? '—')],
        ['Fertilizer Use (kg/ha)', String(params.inputParams.fertilizerUse ?? '—')],
        ['Soil Health Index', String(params.inputParams.soilHealthIndex ?? '—')],
        ['Irrigation Access (%)', String(params.inputParams.irrigationAccess ?? '—')],
      ],
      headStyles: { fillColor: [43, 106, 79] },
      theme: 'grid',
    })
  }

  // Section: Dashboard Metrics
  const yAfterInputs = (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 8 : 44
  doc.setFontSize(13)
  doc.text('Dashboard Metrics (Dataset Average)', 14, yAfterInputs)
  autoTable(doc, {
    startY: yAfterInputs + 4,
    head: [['Metric', 'Value']],
    body: [
      ['Avg Temperature', `${params.metrics.avgTemperature}°C`],
      ['Avg Rainfall / Precipitation', `${params.metrics.avgRainfall} mm`],
      ['Avg Soil Health Index', `${params.metrics.avgSoilHealth}`],
      ['Avg Crop Yield', `${params.metrics.avgYield} MT/ha`],
    ],
    headStyles: { fillColor: [43, 106, 79] },
    theme: 'grid',
  })

  // Section: Prediction Result (if available)
  if (params.predictionResult) {
    const yAfterMetrics = (doc as any).lastAutoTable.finalY + 8
    doc.setFontSize(13)
    doc.text('Prediction Result', 14, yAfterMetrics)
    autoTable(doc, {
      startY: yAfterMetrics + 4,
      head: [['Output', 'Value']],
      body: [
        ['Predicted Yield', `${params.predictionResult.predictedYield} MT/ha`],
        ['Status', params.predictionResult.status],
        ['Confidence', params.predictionResult.confidence],
        ['Adaptation Strategy', params.predictionResult.adaptationStrategy],
        ['Recommendation', params.predictionResult.recommendation],
      ],
      headStyles: { fillColor: [43, 106, 79] },
      theme: 'grid',
    })
  }

  // Section: Recent Data Table
  const yAfterPred = (doc as any).lastAutoTable.finalY + 8
  doc.setFontSize(13)
  doc.text('Recent Dataset Records', 14, yAfterPred)
  autoTable(doc, {
    startY: yAfterPred + 4,
    head: [['Year', 'Country', 'Crop', 'Temp (°C)', 'Precip (mm)', 'Yield (MT/ha)']],
    body: params.tableData.slice(0, 10).map(r => [
      r.year, r.country, r.crop_type,
      r.average_temperature_c?.toFixed(1),
      Math.round(r.total_precipitation_mm),
      r.crop_yield_mt_per_ha?.toFixed(2),
    ]),
    headStyles: { fillColor: [43, 106, 79] },
    theme: 'striped',
  })

  // Footer
  doc.setFontSize(9)
  doc.setTextColor(150)
  doc.text('Generated by YieldSim DSS — Climate-Driven Crop Yield Prediction System', pageWidth / 2, 290, { align: 'center' })

  doc.save(`YieldSim_Report_${params.filters.yearRange}_${new Date().toISOString().split('T')[0]}.pdf`)
}
